# ------------------------------------------------------------
# Bastion SSH configuration
# ------------------------------------------------------------

- name: Remove obsolete Bastion SSH configuration
  ansible.builtin.file:
    path: /etc/ssh/sshd_config.d/90-bastion.conf
    state: absent
  notify: Restart sshd

- name: Configure Bastion-specific SSH settings
  ansible.builtin.copy:
    dest: /etc/ssh/sshd_config.d/00-bastion.conf
    owner: root
    group: root
    mode: "0600"
    content: |
      PubkeyAuthentication yes
      KbdInteractiveAuthentication yes
      UsePAM yes
      AllowTcpForwarding yes

      Match Address {{ public_client_ip }}
          AuthenticationMethods publickey,keyboard-interactive
          PasswordAuthentication no
  notify: Restart sshd
