---
# ============================================================
# ACME - Handlers
# ============================================================

- name: Restart systemd-journald
  ansible.builtin.systemd_service:
    name: systemd-journald
    state: restarted

- name: Reload NetworkManager
  ansible.builtin.systemd_service:
    name: NetworkManager
    state: reloaded

- name: Reload firewalld
  ansible.builtin.systemd_service:
    name: firewalld
    state: reloaded

- name: Restart sshd
  ansible.builtin.systemd_service:
    name: sshd
    state: restarted
