---
#
vault_linux_password_hashes:
  alabelle: "$6$oP6lx2YrZdzo.F2v$FJZ3Fh.ukqk.K9p.Vthd8kkyZUdGf4V1.JcsSMZHkoTYwHQn2mkFYaIUEpfLKqjS.UJyeTT72rT1plIhO9qoT/"
  zlizotte: "$6$RI5P6ksFBrg.Zj1a$xqCD/cLj4IsVyi31r0waUgBkgtM9X4zYRw5VOBjfDnNiufixl2SPmq2iAsu6ZLFN.rexny0OuhUKRz1n/vxjV0"

#
vault_database_password: "Gf8TQsIg3Ux1clB8q2P1LPBQiuNFA+G9"
vault_web_admin_password_hash: "REMPLACER_PAR_HACHAGE_SHA512_CRYPT_ADMIN_WEB"

# Secret TOTP
vault_totp_secrets:
  alabelle: "7725GZZ5Q7IKHEQNQYFZVFWZTVFYUN2O"
  zlizotte: "WUO5FAILVDLHXHICE32RBCN23XN445NV"
