---

# DHCP server configuration (Kea)

- name: Install Kea DHCP server
  ansible.builtin.dnf:
    name: kea
    state: present

# DHCP configuration

- name: Deploy Kea DHCPv4 configuration
  ansible.builtin.template:
    src: kea-dhcp4.conf.j2
    dest: /etc/kea/kea-dhcp4.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart kea-dhcp4

# Service management

- name: Activate and start kea-dhcp4
  ansible.builtin.service:
    name: kea-dhcp4
    state: started
    enabled: true

# Firewall configuration

- name: Authorize DHCP through firewalld
  ansible.posix.firewalld:
    service: dhcp
    permanent: true
    immediate: true
    state: enabled