--- 

# Base system preparation

- name: Update DNF cache
  ansible.builtin.dnf:
    update_cache: true
  changed_when: false

- name: Update packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
   
# Repositories

- name: Install EPEL (Extra Packages for Enterprise Linux)
  ansible.builtin.dnf:
    name: epel-release
    state: present

# Base packages

- name: Install base system packages
  ansible.builtin.dnf:
    name: "{{ installation_packages }}"
    state: present

# Firewall install

- name: Install firewalld
  ansible.builtin.dnf:
    name: firewalld
    state: present

- name: Activate and start firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true
