---

# FTP / vsftpd server configuration

- name: Install vsftpd
  ansible.builtin.dnf:
    name: vsftpd
    state: present

# FTP configuration

- name: Deploy vsftpd configuration
  ansible.builtin.template:
    src: vsftpd.conf.j2
    dest: /etc/vsftpd/vsftpd.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart vsftpd

# Service management

- name: Activate and start vsftpd
  ansible.builtin.service:
    name: vsftpd
    state: started
    enabled: true
  

# Firewall configuration

- name: Authorize FTP through firewalld
  ansible.posix.firewalld:
    service: ftp
    permanent: true
    immediate: true
    state: enabled