---

# Set system hostname

- name: Configure system hostname
  ansible.builtin.hostname:
    name: "{{ hostname_fqdn }}"

# Ensure hostname resolves locally

- name: Ensure hostname is present in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^{{ dns_server_ip }}\\s+"
    line: "{{ dns_server_ip }} {{ hostname_fqdn }} {{ hostname_fqdn.split('.')[0] }}"