---

# Essentials configuration variables

username: fabhoule
hostname_fqdn: "centos.fabhoule.ca"

installation_packages:
  - vim
  - nano
  - curl
  - wget
  - git
  - net-tools

# General network variables

domain_name: "fabhoule.ca"
dns_domain: "fabhoule.ca"
dns_server_ip: "172.16.200.12"
dns_network: "172.16.200.0/24"

# DNS records: forward zone variables

dns_ns: "ns1.fabhoule.ca"
dns_admin_email: "webmestre"
dns_serial: "2026061501"
forward_zone_file: "/var/named/db.fabhoule.ca"

dns_records:
  - name: "@"
    type: A
    value: "172.16.200.12"

  - name: "centos"
    type: A
    value: "172.16.200.12"

  - name: "ns1"
    type: A
    value: "172.16.200.12"

  - name: "www"
    type: A
    value: "172.16.200.12"

  - name: "ftp"
    type: A
    value: "172.16.200.12"

# DNS records: reverse zone variables

reverse_zone: "200.16.172.in-addr.arpa"
reverse_zone_file: "172.16.200"
reverse_zone_path: "/var/named/db.172.16.200"
reverse_octet: "12"

# DHCP variables

dhcp_network: "172.16.200.0"
dhcp_subnet: "24"

dhcp_range_start: "172.16.200.101"
dhcp_range_end: "172.16.200.110"

dhcp_gateway: "172.16.200.2"

dhcp_default_lease_time: 864000
dhcp_max_lease_time: 5184000

windows_client_mac: "00:E0:4C:68:02:F5"
windows_client_ip: "172.16.200.20"

# FTP variables

ftp_local_enable: "YES"
ftp_write_enable: "YES"
ftp_anonymous_enable: "NO"

# NTP variables

ntp_pool: "ca.pool.ntp.org"
ntp_network: "172.16.200.0/24"

# Samba variables

samba_share_name: "samba_shares"
samba_share_root: "/mnt/monpartage"
samba_share_path: "/mnt/monpartage/samba_shares"
samba_server_string: "Samba Server"

samba_user: "fabhoule"

# NFS variables

nfs_share_path: "/mnt/monpartage/nfs_shares"
nfs_allowed_network: "172.16.200.0/24"