---
- name: Reload firewalld
  ansible.builtin.command: firewall-cmd --reload

- name: Restart journald
  ansible.builtin.systemd_service:
    name: systemd-journald
    state: restarted
  notify: Flush journal

- name: Flush journal
  ansible.builtin.command: journalctl --flush
  changed_when: false

- name: Restart named
  ansible.builtin.systemd_service:
    name: named
    state: restarted

- name: Restart chronyd
  ansible.builtin.systemd_service:
    name: chronyd
    state: restarted

- name: Restart rsyslog
  ansible.builtin.systemd_service:
    name: rsyslog
    state: restarted

- name: Restart fail2ban
  ansible.builtin.systemd_service:
    name: fail2ban
    state: restarted

- name: Restart mariadb
  ansible.builtin.systemd_service:
    name: mariadb
    state: restarted

- name: Restart php-fpm
  ansible.builtin.systemd_service:
    name: php-fpm
    state: restarted

- name: Reload nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: reloaded

- name: Reload sshd
  ansible.builtin.systemd_service:
    name: sshd
    state: reloaded

- name: Load audit rules
  ansible.builtin.command: augenrules --load
