---
- name: Configurer infra comme serveur NTP
  ansible.builtin.template:
    src: chrony-server.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart chronyd

- name: Demarrer Chrony sur infra
  ansible.builtin.systemd_service:
    name: chronyd
    state: started
    enabled: true
