---
- name: Lire les services presents
  ansible.builtin.service_facts:

- name: Arreter les services de l'ancien mandat
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop: "{{ unnecessary_services }}"
  when: (item ~ '.service') in ansible_facts.services

- name: Retirer les paquets de l'ancien mandat
  ansible.builtin.dnf:
    name: "{{ unnecessary_packages }}"
    state: absent

- name: Retirer les anciens comptes explicitement identifies
  ansible.builtin.user:
    name: "{{ item }}"
    state: absent
    remove: true
  loop: "{{ unnecessary_accounts }}"
