---
- name: Installer BIND
  ansible.builtin.dnf:
    name: [bind, bind-utils]
    state: present

- name: Deployer la zone DNS autoritaire
  ansible.builtin.template:
    src: db.acme.lan.j2
    dest: "{{ forward_zone_file }}"
    owner: root
    group: named
    mode: "0640"
    validate: "/usr/sbin/named-checkzone {{ dns_domain }} %s"
  notify: Restart named

- name: Deployer named.conf
  ansible.builtin.template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: "0640"
    validate: /usr/sbin/named-checkconf %s
  notify: Restart named

- name: Restaurer les contextes SELinux de BIND
  ansible.builtin.command: restorecon -Rv /etc/named.conf /var/named
  register: acme_named_labels
  changed_when: acme_named_labels.stdout | length > 0

- name: Verifier la configuration et les zones
  ansible.builtin.command: named-checkconf -z /etc/named.conf
  changed_when: false

- name: Demarrer BIND
  ansible.builtin.systemd_service:
    name: named
    state: started
    enabled: true
