---
- name: Configurer le hostname propre a chaque serveur
  ansible.builtin.hostname:
    name: "{{ hostname_fqdn }}"

- name: Ajouter la resolution locale des trois serveurs
  ansible.builtin.blockinfile:
    path: /etc/hosts
    marker: "# {mark} ACME MANAGED HOSTS"
    block: |
      {{ bastion_public_ip }} bastion.{{ domain_name }} bastion
      {{ web_public_ip }} web.{{ domain_name }} web {{ web_server_name }}
      {{ infra_public_ip }} infra.{{ domain_name }} infra
