---
- name: Base commune ACME
  hosts: servers
  become: true
  pre_tasks:
    - ansible.builtin.import_tasks: tasks/preflight.yml
  tasks:
    - ansible.builtin.import_tasks: tasks/essentials.yml
    - ansible.builtin.import_tasks: tasks/hostname.yml
    - ansible.builtin.import_tasks: tasks/users.yml
    - ansible.builtin.import_tasks: tasks/selinux.yml
    - ansible.builtin.import_tasks: tasks/journald.yml
    - ansible.builtin.import_tasks: tasks/sudo.yml
    - ansible.builtin.import_tasks: tasks/firewalld.yml
    - ansible.builtin.import_tasks: tasks/cleanup.yml
  handlers:
    - ansible.builtin.import_tasks: handlers/main.yml

- name: Infrastructure DNS temps et journaux
  hosts: infra
  become: true
  tasks:
    - ansible.builtin.import_tasks: tasks/dns.yml
    - ansible.builtin.import_tasks: tasks/chrony_server.yml
    - ansible.builtin.import_tasks: tasks/rsyslog_server.yml
    - ansible.builtin.import_tasks: tasks/openscap.yml
  handlers:
    - ansible.builtin.import_tasks: handlers/main.yml

- name: Bastion controleur MFA et Fail2ban
  hosts: bastion
  become: true
  tasks:
    - ansible.builtin.import_tasks: tasks/ansible_controller.yml
    - ansible.builtin.import_tasks: tasks/totp.yml
    - ansible.builtin.import_tasks: tasks/fail2ban.yml
  handlers:
    - ansible.builtin.import_tasks: handlers/main.yml

- name: Serveur web et base de donnees locale
  hosts: web
  become: true
  tasks:
    - ansible.builtin.import_tasks: tasks/mariadb.yml
    - ansible.builtin.import_tasks: tasks/nginx.yml
  handlers:
    - ansible.builtin.import_tasks: handlers/main.yml

- name: Clients NTP et expedition des journaux
  hosts: bastion:web
  become: true
  tasks:
    - ansible.builtin.import_tasks: tasks/chrony_client.yml
    - ansible.builtin.import_tasks: tasks/rsyslog_client.yml
  handlers:
    - ansible.builtin.import_tasks: handlers/main.yml

- name: Finaliser le reseau SSH et auditd
  hosts: servers
  become: true
  tasks:
    - ansible.builtin.import_tasks: tasks/networking.yml
    - ansible.builtin.import_tasks: tasks/ssh_common.yml
    - ansible.builtin.import_tasks: tasks/auditd.yml
  handlers:
    - ansible.builtin.import_tasks: handlers/main.yml
